title: Fight for $15 at The Ohio State University
description: A campaign demanding a living wage for all university workers at The Ohio State University.
url: "https://fightfor15osu.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ff15osu
social_image: /images/cards/ff15osu-default.png

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
